name: CI

on:
  push:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Installer ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          wget -N https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run tests
        run: |
          xvfb-run --server-args='-screen 0 1024x768x24' python -m unittest discover -s "Tests et intégration continue" -p "test_*.py"