name: CI

on:
  push:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Installer Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Vérifier l'installation de Chrome
        run: google-chrome --version

      - name: Télécharger et installer ChromeDriver
        run: |
          sudo apt-get install -y curl unzip
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          wget -N https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Vérifier l'installation de ChromeDriver
        run: chromedriver --version

      - name: Run tests avec debug
        run: |
          export DISPLAY=:99
          xvfb-run --server-args="-screen 0 1920x1080x24" python -m unittest discover -s tests -p "test_*.py"
