name: Selenium Workflow

on:
  push:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Installer les dépendances (sans requirements.txt)
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Exécuter les tests avec unittest
        run: |
          python -m unittest discover -s "Tests et intégration continue" -p "test_*.py"
